<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('cities')->insert([
            ['name' => 'arica','label'=>'Arica'],
            ['name' => 'camarones','label'=>'Camarones'],
            ['name' => 'putre','label'=>'Putre'],
            ['name' => 'general lagos','label'=>'General Lagos'],
            ['name' => 'iquique','label'=>'Iquique'],
            ['name' => 'alto hospicio','label'=>'Alto Hospicio'],
            ['name' => 'pozo almonte','label'=>'Pozo Almonte'],
            ['name' => 'camina','label'=>'Camiña'],
            ['name' => 'colchane','label'=>'Colchane'],
            ['name' => 'huara','label'=>'Huara'],
            ['name' => 'pica','label'=>'Pica'],
            ['name' => 'antofagasta','label'=>'Antofagasta'],
            ['name' => 'mejillones','label'=>'Mejillones'],
            ['name' => 'sierra gorda','label'=>'Sierra Gorda'],
            ['name' => 'taltal','label'=>'Taltal'],
            ['name' => 'calama','label'=>'Calama'],
            ['name' => 'ollague','label'=>'Ollagüe'],
            ['name' => 'san pedro de atacama','label'=>'San Pedro de Atacama'],
            ['name' => 'tocopilla','label'=>'Tocopilla'],
            ['name' => 'maria elena','label'=>'María Elena'],
            ['name' => 'copiapo','label'=>'Copiapó'],
            ['name' => 'caldera','label'=>'Caldera'],
            ['name' => 'tierra amarilla','label'=>'Tierra Amarilla'],
            ['name' => 'chanaral','label'=>'Chañaral'],
            ['name' => 'diego de almagro','label'=>'Diego de Almagro'],
            ['name' => 'vallenar','label'=>'Vallenar'],
            ['name' => 'alto del carmen','label'=>'Alto del Carmen'],
            ['name' => 'freirina','label'=>'Freirina'],
            ['name' => 'huasco','label'=>'Huasco'],
            ['name' => 'la serena','label'=>'La Serena'],
            ['name' => 'coquimbo','label'=>'Coquimbo'],
            ['name' => 'andacollo','label'=>'Andacollo'],
            ['name' => 'la higuera','label'=>'La Higuera'],
            ['name' => 'paiguano','label'=>'Paiguano'],
            ['name' => 'vicuna','label'=>'Vicuña'],
            ['name' => 'illapel','label'=>'Illapel'],
            ['name' => 'canela','label'=>'Canela'],
            ['name' => 'los vilos','label'=>'Los Vilos'],
            ['name' => 'salamanca','label'=>'Salamanca'],
            ['name' => 'ovalle','label'=>'Ovalle'],
            ['name' => 'combarbala','label'=>'Combarbalá'],
            ['name' => 'monte patria','label'=>'Monte Patria'],
            ['name' => 'punitaqui','label'=>'Punitaqui'],
            ['name' => 'rio hurtado','label'=>'Río Hurtado'],
            ['name' => 'valparaiso','label'=>'Valparaíso' ],
            ['name' => 'casablanca','label'=>'Casablanca' ],
            ['name' => 'concon','label'=>'Concón' ],
            ['name' => 'juan fernandez','label'=>'Juan Fernández' ],
            ['name' => 'puchuncavi','label'=>'Puchuncaví' ],
            ['name' => 'quilpue','label'=>'Quilpué' ],
            ['name' => 'quintero','label'=>'Quintero' ],
            ['name' => 'villa alemana','label'=>'Villa Alemana' ],
            ['name' => 'vina del mar','label'=>'Viña del Mar' ],
            ['name' => 'isla de pascua','label'=>'Isla de Pascua' ],
            ['name' => 'los andes','label'=>'Los Andes' ],
            ['name' => 'calle larga','label'=>'Calle Larga' ],
            ['name' => 'rinconada','label'=>'Rinconada' ],
            ['name' => 'san esteban','label'=>'San Esteban' ],
            ['name' => 'la ligua','label'=>'La Ligua' ],
            ['name' => 'cabildo','label'=>'Cabildo' ],
            ['name' => 'papudo','label'=>'Papudo' ],
            ['name' => 'petorca','label'=>'Petorca' ],
            ['name' => 'zapallar','label'=>'Zapallar' ],
            ['name' => 'quillota','label'=>'Quillota' ],
            ['name' => 'calera','label'=>'Calera' ],
            ['name' => 'hijuelas','label'=>'Hijuelas' ],
            ['name' => 'la cruz','label'=>'La Cruz' ],
            ['name' => 'limache','label'=>'Limache' ],
            ['name' => 'nogales','label'=>'Nogales' ],
            ['name' => 'olmue','label'=>'Olmué' ],
            ['name' => 'san antonio','label'=>'San Antonio' ],
            ['name' => 'algarrobo','label'=>'Algarrobo' ],
            ['name' => 'cartagena','label'=>'Cartagena' ],
            ['name' => 'el quisco','label'=>'El Quisco' ],
            ['name' => 'el tabo','label'=>'El Tabo' ],
            ['name' => 'santo domingo','label'=>'Santo Domingo' ],
            ['name' => 'san felipe','label'=>'San Felipe' ],
            ['name' => 'catemu','label'=>'Catemu' ],
            ['name' => 'llaillay','label'=>'Llaillay' ],
            ['name' => 'panquehue','label'=>'Panquehue' ],
            ['name' => 'putaendo','label'=>'Putaendo' ],
            ['name' => 'santa maria','label'=>'Santa María' ],
            ['name' => 'rancagua','label'=>'Rancagua' ],
            ['name' => 'codegua','label'=>'Codegua' ],
            ['name' => 'coinco','label'=>'Coinco' ],
            ['name' => 'coltauco','label'=>'Coltauco' ],
            ['name' => 'donihue','label'=>'Doñihue' ],
            ['name' => 'graneros','label'=>'Graneros' ],
            ['name' => 'las cabras','label'=>'Las Cabras' ],
            ['name' => 'machali','label'=>'Machalí' ],
            ['name' => 'malloa','label'=>'Malloa' ],
            ['name' => 'mostazal','label'=>'Mostazal' ],
            ['name' => 'olivar','label'=>'Olivar' ],
            ['name' => 'peumo','label'=>'Peumo' ],
            ['name' => 'pichidegua','label'=>'Pichidegua' ],
            ['name' => 'quinta de tilcoco','label'=>'Quinta de Tilcoco' ],
            ['name' => 'rengo','label'=>'Rengo' ],
            ['name' => 'requinoa','label'=>'Requínoa' ],
            ['name' => 'san vicente','label'=>'San Vicente' ],
            ['name' => 'pichilemu','label'=>'Pichilemu' ],
            ['name' => 'la estrella','label'=>'La Estrella' ],
            ['name' => 'litueche','label'=>'Litueche' ],
            ['name' => 'marchihue','label'=>'Marchihue' ],
            ['name' => 'navidad','label'=>'Navidad' ],
            ['name' => 'paredones','label'=>'Paredones' ],
            ['name' => 'san fernando','label'=>'San Fernando' ],
            ['name' => 'chepica','label'=>'Chépica' ],
            ['name' => 'chimbarongo','label'=>'Chimbarongo' ],
            ['name' => 'lolol','label'=>'Lolol' ],
            ['name' => 'nancagua','label'=>'Nancagua' ],
            ['name' => 'palmilla','label'=>'Palmilla' ],
            ['name' => 'peralillo','label'=>'Peralillo' ],
            ['name' => 'placilla','label'=>'Placilla' ],
            ['name' => 'pumanque','label'=>'Pumanque' ],
            ['name' => 'santa cruz','label'=>'Santa Cruz' ],
            ['name' => 'talca','label'=>'Talca' ],
            ['name' => 'constitucion','label'=>'Constitución' ],
            ['name' => 'curepto','label'=>'Curepto' ],
            ['name' => 'empedrado','label'=>'Empedrado' ],
            ['name' => 'maule','label'=>'Maule' ],
            ['name' => 'pelarco','label'=>'Pelarco' ],
            ['name' => 'pencahue','label'=>'Pencahue' ],
            ['name' => 'rio claro','label'=>'Río Claro' ],
            ['name' => 'san clemente','label'=>'San Clemente' ],
            ['name' => 'san rafael','label'=>'San Rafael' ],
            ['name' => 'cauquenes','label'=>'Cauquenes' ],
            ['name' => 'chanco','label'=>'Chanco' ],
            ['name' => 'pelluhue','label'=>'Pelluhue' ],
            ['name' => 'curico','label'=>'Curicó' ],
            ['name' => 'hualane','label'=>'Hualañé' ],
            ['name' => 'licanten','label'=>'Licantén' ],
            ['name' => 'molina','label'=>'Molina' ],
            ['name' => 'rauco','label'=>'Rauco' ],
            ['name' => 'romeral','label'=>'Romeral' ],
            ['name' => 'sagrada familia','label'=>'Sagrada Familia' ],
            ['name' => 'teno','label'=>'Teno' ],
            ['name' => 'vichuquen','label'=>'Vichuquén' ],
            ['name' => 'linares','label'=>'Linares' ],
            ['name' => 'colbun','label'=>'Colbún' ],
            ['name' => 'longavi','label'=>'Longaví' ],
            ['name' => 'parral','label'=>'Parral' ],
            ['name' => 'retiro','label'=>'Retiro' ],
            ['name' => 'san javier','label'=>'San Javier' ],
            ['name' => 'villa alegre','label'=>'Villa Alegre' ],
            ['name' => 'yerbas buenas','label'=>'Yerbas Buenas' ],
            ['name' => 'concepcion','label'=>'Concepción' ],
            ['name' => 'coronel','label'=>'Coronel' ],
            ['name' => 'chiguayante','label'=>'Chiguayante' ],
            ['name' => 'florida','label'=>'Florida' ],
            ['name' => 'hualqui','label'=>'Hualqui' ],
            ['name' => 'lota','label'=>'Lota' ],
            ['name' => 'penco','label'=>'Penco' ],
            ['name' => 'san pedro de la paz','label'=>'San Pedro de la Paz' ],
            ['name' => 'santa juana','label'=>'Santa Juana' ],
            ['name' => 'talcahuano','label'=>'Talcahuano' ],
            ['name' => 'tome','label'=>'Tomé' ],
            ['name' => 'hualpen','label'=>'Hualpén' ],
            ['name' => 'lebu','label'=>'Lebu' ],
            ['name' => 'arauco','label'=>'Arauco' ],
            ['name' => 'canete','label'=>'Cañete' ],
            ['name' => 'contulmo','label'=>'Contulmo' ],
            ['name' => 'curanilahue','label'=>'Curanilahue' ],
            ['name' => 'los alamos','label'=>'Los Álamos' ],
            ['name' => 'tirua','label'=>'Tirúa' ],
            ['name' => 'los angeles','label'=>'Los Ángeles' ],
            ['name' => 'antuco','label'=>'Antuco' ],
            ['name' => 'cabrero','label'=>'Cabrero' ],
            ['name' => 'laja','label'=>'Laja' ],
            ['name' => 'mulchen','label'=>'Mulchén' ],
            ['name' => 'nacimiento','label'=>'Nacimiento' ],
            ['name' => 'negrete','label'=>'Negrete' ],
            ['name' => 'quilaco','label'=>'Quilaco' ],
            ['name' => 'quilleco','label'=>'Quilleco' ],
            ['name' => 'san rosendo','label'=>'San Rosendo' ],
            ['name' => 'santa barbara','label'=>'Santa Bárbara' ],
            ['name' => 'tucapel','label'=>'Tucapel' ],
            ['name' => 'yumbel','label'=>'Yumbel' ],
            ['name' => 'alto biobio','label'=>'Alto Biobío' ],
            ['name' => 'chillan','label'=>'Chillán' ],
            ['name' => 'bulnes','label'=>'Bulnes' ],
            ['name' => 'cobquecura','label'=>'Cobquecura' ],
            ['name' => 'coelemu','label'=>'Coelemu' ],
            ['name' => 'coihueco','label'=>'Coihueco' ],
            ['name' => 'chillan viejo','label'=>'Chillán Viejo' ],
            ['name' => 'el carmen','label'=>'El Carmen' ],
            ['name' => 'ninhue','label'=>'Ninhue' ],
            ['name' => 'niquen','label'=>'Ñiquén' ],
            ['name' => 'pemuco','label'=>'Pemuco' ],
            ['name' => 'pinto','label'=>'Pinto' ],
            ['name' => 'portezuelo','label'=>'Portezuelo' ],
            ['name' => 'quillon','label'=>'Quillón' ],
            ['name' => 'quirihue','label'=>'Quirihue' ],
            ['name' => 'ranquil','label'=>'Ránquil' ],
            ['name' => 'san carlos','label'=>'San Carlos' ],
            ['name' => 'san fabian','label'=>'San Fabián' ],
            ['name' => 'san ignacio','label'=>'San Ignacio' ],
            ['name' => 'san nicolas','label'=>'San Nicolás' ],
            ['name' => 'treguaco','label'=>'Treguaco' ],
            ['name' => 'yungay','label'=>'Yungay' ],
            ['name' => 'temuco','label'=>'Temuco' ],
            ['name' => 'carahue','label'=>'Carahue' ],
            ['name' => 'cunco','label'=>'Cunco' ],
            ['name' => 'curarrehue','label'=>'Curarrehue' ],
            ['name' => 'freire','label'=>'Freire' ],
            ['name' => 'galvarino','label'=>'Galvarino' ],
            ['name' => 'gorbea','label'=>'Gorbea' ],
            ['name' => 'lautaro','label'=>'Lautaro' ],
            ['name' => 'loncoche','label'=>'Loncoche' ],
            ['name' => 'melipeuco','label'=>'Melipeuco' ],
            ['name' => 'nueva imperial','label'=>'Nueva Imperial' ],
            ['name' => 'padre las casas','label'=>'Padre Las Casas' ],
            ['name' => 'perquenco','label'=>'Perquenco' ],
            ['name' => 'pitrufquen','label'=>'Pitrufquén' ],
            ['name' => 'pucon','label'=>'Pucón' ],
            ['name' => 'saavedra','label'=>'Saavedra' ],
            ['name' => 'teodoro schmidt','label'=>'Teodoro Schmidt' ],
            ['name' => 'tolten','label'=>'Toltén' ],
            ['name' => 'vilcun','label'=>'Vilcún' ],
            ['name' => 'villarrica','label'=>'Villarrica' ],
            ['name' => 'cholchol','label'=>'Cholchol' ],
            ['name' => 'angol','label'=>'Angol' ],
            ['name' => 'collipulli','label'=>'Collipulli' ],
            ['name' => 'curacautin','label'=>'Curacautín' ],
            ['name' => 'ercilla','label'=>'Ercilla' ],
            ['name' => 'lonquimay','label'=>'Lonquimay' ],
            ['name' => 'los sauces','label'=>'Los Sauces' ],
            ['name' => 'lumaco','label'=>'Lumaco' ],
            ['name' => 'puren','label'=>'Purén' ],
            ['name' => 'renaico','label'=>'Renaico' ],
            ['name' => 'traiguen','label'=>'Traiguén' ],
            ['name' => 'victoria','label'=>'Victoria' ],
            ['name' => 'valdivia','label'=>'Valdivia' ],
            ['name' => 'corral','label'=>'Corral' ],
            ['name' => 'lanco','label'=>'Lanco' ],
            ['name' => 'los lagos','label'=>'Los Lagos' ],
            ['name' => 'mafil','label'=>'Máfil' ],
            ['name' => 'mariquina','label'=>'Mariquina' ],
            ['name' => 'paillaco','label'=>'Paillaco' ],
            ['name' => 'panguipulli','label'=>'Panguipulli' ],
            ['name' => 'la union','label'=>'La Unión' ],
            ['name' => 'futrono','label'=>'Futrono' ],
            ['name' => 'lago ranco','label'=>'Lago Ranco' ],
            ['name' => 'rio bueno','label'=>'Río Bueno' ],
            ['name' => 'puerto montt','label'=>'Puerto Montt' ],
            ['name' => 'calbuco','label'=>'Calbuco' ],
            ['name' => 'cochamo','label'=>'Cochamó' ],
            ['name' => 'fresia','label'=>'Fresia' ],
            ['name' => 'frutillar','label'=>'Frutillar' ],
            ['name' => 'los muermos','label'=>'Los Muermos' ],
            ['name' => 'llanquihue','label'=>'Llanquihue' ],
            ['name' => 'maullin','label'=>'Maullín' ],
            ['name' => 'puerto varas','label'=>'Puerto Varas' ],
            ['name' => 'castro','label'=>'Castro' ],
            ['name' => 'ancud','label'=>'Ancud' ],
            ['name' => 'chonchi','label'=>'Chonchi' ],
            ['name' => 'curaco de velez','label'=>'Curaco de Vélez' ],
            ['name' => 'dalcahue','label'=>'Dalcahue' ],
            ['name' => 'puqueldon','label'=>'Puqueldón' ],
            ['name' => 'queilen','label'=>'Queilén' ],
            ['name' => 'quellon','label'=>'Quellón' ],
            ['name' => 'quemchi','label'=>'Quemchi' ],
            ['name' => 'quinchao','label'=>'Quinchao' ],
            ['name' => 'osorno','label'=>'Osorno' ],
            ['name' => 'puerto octay','label'=>'Puerto Octay' ],
            ['name' => 'purranque','label'=>'Purranque' ],
            ['name' => 'puyehue','label'=>'Puyehue' ],
            ['name' => 'rio negro','label'=>'Río Negro' ],
            ['name' => 'san juan de la costa','label'=>'San Juan de la Costa' ],
            ['name' => 'san pablo','label'=>'San Pablo' ],
            ['name' => 'chaiten','label'=>'Chaitén' ],
            ['name' => 'futaleufu','label'=>'Futaleufú' ],
            ['name' => 'hualaihue','label'=>'Hualaihué' ],
            ['name' => 'palena','label'=>'Palena' ],
            ['name' => 'coyhaique','label'=>'Coyhaique' ],
            ['name' => 'lago verde','label'=>'Lago Verde' ],
            ['name' => 'aysen','label'=>'Aysén' ],
            ['name' => 'cisnes','label'=>'Cisnes' ],
            ['name' => 'guaitecas','label'=>'Guaitecas' ],
            ['name' => 'cochrane','label'=>'Cochrane' ],
            ['name' => 'ohiggins','label'=>'O\'Higgins' ],
            ['name' => 'tortel','label'=>'Tortel' ],
            ['name' => 'chile chico','label'=>'Chile Chico' ],
            ['name' => 'rio ibanez','label'=>'Río Ibáñez' ],
            ['name' => 'punta arenas','label'=>'Punta Arenas' ],
            ['name' => 'laguna blanca','label'=>'Laguna Blanca' ],
            ['name' => 'rio verde','label'=>'Río Verde' ],
            ['name' => 'san gregorio','label'=>'San Gregorio' ],
            ['name' => 'cabo de hornos (ex - navarino)','label'=>'Cabo de Hornos (Ex - Navarino)' ],
            ['name' => 'antartica','label'=>'Antártica' ],
            ['name' => 'porvenir','label'=>'Porvenir' ],
            ['name' => 'primavera','label'=>'Primavera' ],
            ['name' => 'timaukel','label'=>'Timaukel' ],
            ['name' => 'natales','label'=>'Natales' ],
            ['name' => 'torres del paine','label'=>'Torres del Paine' ],
            ['name' => 'santiago','label'=>'Santiago' ],
            ['name' => 'cerrillos','label'=>'Cerrillos' ],
            ['name' => 'cerro navia','label'=>'Cerro Navia' ],
            ['name' => 'conchali','label'=>'Conchalí' ],
            ['name' => 'el bosque','label'=>'El Bosque' ],
            ['name' => 'estacion central','label'=>'Estación Central' ],
            ['name' => 'huechuraba','label'=>'Huechuraba' ],
            ['name' => 'independencia','label'=>'Independencia' ],
            ['name' => 'la cisterna','label'=>'La Cisterna' ],
            ['name' => 'la florida','label'=>'La Florida' ],
            ['name' => 'la granja','label'=>'La Granja' ],
            ['name' => 'la pintana','label'=>'La Pintana' ],
            ['name' => 'la reina','label'=>'La Reina' ],
            ['name' => 'las condes','label'=>'Las Condes' ],
            ['name' => 'lo barnechea','label'=>'Lo Barnechea' ],
            ['name' => 'lo espejo','label'=>'Lo Espejo' ],
            ['name' => 'lo prado','label'=>'Lo Prado' ],
            ['name' => 'macul','label'=>'Macul' ],
            ['name' => 'maipu','label'=>'Maipú' ],
            ['name' => 'nunoa','label'=>'Ñuñoa' ],
            ['name' => 'pedro aguirre cerda','label'=>'Pedro Aguirre Cerda' ],
            ['name' => 'penalolen','label'=>'Peñalolén' ],
            ['name' => 'providencia','label'=>'Providencia' ],
            ['name' => 'pudahuel','label'=>'Pudahuel' ],
            ['name' => 'quilicura','label'=>'Quilicura' ],
            ['name' => 'quinta normal','label'=>'Quinta Normal' ],
            ['name' => 'recoleta','label'=>'Recoleta' ],
            ['name' => 'renca','label'=>'Renca' ],
            ['name' => 'san joaquin','label'=>'San Joaquín' ],
            ['name' => 'san miguel','label'=>'San Miguel' ],
            ['name' => 'san ramon','label'=>'San Ramón' ],
            ['name' => 'vitacura','label'=>'Vitacura' ],
            ['name' => 'puente alto','label'=>'Puente Alto' ],
            ['name' => 'pirque','label'=>'Pirque' ],
            ['name' => 'san jose de maipo','label'=>'San José de Maipo' ],
            ['name' => 'colina','label'=>'Colina' ],
            ['name' => 'lampa','label'=>'Lampa' ],
            ['name' => 'tiltil','label'=>'Tiltil' ],
            ['name' => 'san bernardo','label'=>'San Bernardo' ],
            ['name' => 'buin','label'=>'Buin' ],
            ['name' => 'calera de tango','label'=>'Calera de Tango' ],
            ['name' => 'paine','label'=>'Paine' ],
            ['name' => 'melipilla','label'=>'Melipilla' ],
            ['name' => 'alhue','label'=>'Alhué' ],
            ['name' => 'curacavi','label'=>'Curacaví' ],
            ['name' => 'maria pinto','label'=>'María Pinto' ],
            ['name' => 'san pedro','label'=>'San Pedro' ],
            ['name' => 'talagante','label'=>'Talagante' ],
            ['name' => 'el monte','label'=>'El Monte' ],
            ['name' => 'isla de maipo','label'=>'Isla de Maipo' ],
            ['name' => 'padre hurtado','label'=>'Padre Hurtado' ],
            ['name' => 'penaflor','label'=>'Peñaflor' ]
        ]);
    }
}
